# -*- coding: utf-8 -*-

LISTMUNI = [u'001 ABÁIGAR',
            u'002 ABÁRZUZA/ABARTZUZA',
            u'003 ABAURREGAINA/ABAURREA ALTA',
            u'004 ABAURREPEA/ABAURREA BAJA',
            u'005 ABERIN',
            u'006 ABLITAS',
            u'007 ADIÓS',
            u'008 AGUILAR DE CODÉS',
            u'009 AIBAR/OIBAR',
            u'011 ALLÍN/ALLIN',
            u'012 ALLO',
            u'010 ALTSASU/ALSASUA',
            u'013 AMÉSCOA BAJA',
            u'014 ANCÍN/ANTZIN',
            u'015 ANDOSILLA',
            u'016 ANSOÁIN/ANTSOAIN',
            u'017 ANUE',
            u'018 AÑORBE',
            u'019 AOIZ/AGOITZ',
            u'020 ARAITZ',
            u'025 ARAKIL',
            u'021 ARANARACHE/ARANARATXE',
            u'023 ARANGUREN',
            u'024 ARANO',
            u'022 ARANTZA',
            u'026 ARAS',
            u'027 ARBIZU',
            u'028 ARCE/ARTZI',
            u'030 ARELLANO',
            u'031 ARESO',
            u'032 ARGUEDAS',
            u'033 ARIA',
            u'034 ARIBE',
            u'035 ARMAÑANZAS',
            u'036 ARRÓNIZ',
            u'037 ARRUAZU',
            u'038 ARTAJONA',
            u'039 ARTAZU',
            u'040 ATETZ/ATEZ',
            u'058 AURITZ/BURGUETE',
            u'041 AYEGUI/AIEGI',
            u'042 AZAGRA',
            u'043 AZUELO',
            u'044 BAKAIKU',
            u'901 BARAÑÁIN/BARAÑAIN',
            u'045 BARÁSOAIN',
            u'046 BARBARIN',
            u'047 BARGOTA',
            u'048 BARILLAS',
            u'049 BASABURUA',
            u'050 BAZTAN',
            u'137 BEINTZA-LABAIEN',
            u'051 BEIRE',
            u'052 BELASCOÁIN',
            u'250 BERA',
            u'053 BERBINZANA',
            u'905 BERIÁIN',
            u'902 BERRIOPLANO/BERRIOBEITI',
            u'903 BERRIOZAR',
            u'054 BERTIZARANA',
            u'055 BETELU',
            u'253 BIDAURRETA',
            u'056 BIURRUN-OLCOZ',
            u'057 BUÑUEL',
            u'059 BURGUI/BURGI',
            u'060 BURLADA/BURLATA',
            u'062 CABANILLAS',
            u'063 CABREDO',
            u'064 CADREITA',
            u'065 CAPARROSO',
            u'066 CÁRCAR',
            u'067 CARCASTILLO',
            u'068 CASCANTE',
            u'069 CÁSEDA',
            u'070 CASTEJÓN',
            u'071 CASTILLONUEVO',
            u'193 CENDEA DE OLZA/OLTZA ZENDEA',
            u'072 CINTRUÉNIGO',
            u'074 CIRAUQUI/ZIRAUKI',
            u'075 CIRIZA/ZIRITZA',
            u'076 CIZUR',
            u'077 CORELLA',
            u'078 CORTES',
            u'079 DESOJO',
            u'080 DICASTILLO',
            u'081 DONAMARIA',
            u'221 DONEZTEBE/SANTESTEBAN',
            u'083 ECHARRI/ETXARRI',
            u'061 EL BUSTO',
            u'087 ELGORRIAGA',
            u'089 ENÉRIZ/ENERITZ',
            u'090 ERATSUN',
            u'091 ERGOIENA',
            u'092 ERRO',
            u'094 ESLAVA',
            u'095 ESPARZA DE SALAZAR/ESPARTZA ZARAITZU',
            u'096 ESPRONCEDA',
            u'097 ESTELLA-LIZARRA',
            u'098 ESTERIBAR',
            u'099 ETAYO',
            u'082 ETXALAR',
            u'084 ETXARRI ARANATZ',
            u'085 ETXAURI',
            u'100 EULATE',
            u'101 EZCABARTE',
            u'093 EZCÁROZ/EZKAROZE',
            u'102 EZKURRA',
            u'103 EZPROGUI',
            u'104 FALCES',
            u'105 FITERO',
            u'106 FONTELLAS',
            u'107 FUNES',
            u'108 FUSTIÑANA',
            u'109 GALAR',
            u'110 GALLIPIENZO/GALIPENTZU',
            u'111 GALLUÉS/GALOZE',
            u'112 GARAIOA',
            u'113 GARDE',
            u'114 GARÍNOAIN',
            u'115 GARRALDA',
            u'116 GENEVILLA',
            u'117 GOIZUETA',
            u'118 GOÑI',
            u'119 GÜESA/GORZA',
            u'120 GUESÁLAZ/GESALATZ',
            u'121 GUIRGUILLANO',
            u'256 HIRIBERRI/VILLANUEVA DE AEZKOA',
            u'122 HUARTE/UHARTE',
            u'124 IBARGOITI',
            u'259 IGANTZI',
            u'125 IGÚZQUIZA',
            u'126 IMOTZ',
            u'127 IRAÑETA',
            u'904 IRURTZUN',
            u'128 ISABA/IZABA',
            u'129 ITUREN',
            u'130 ITURMENDI',
            u'131 IZA/ITZA',
            u'132 IZAGAONDOA',
            u'133 IZALZU/ITZALTZU',
            u'134 JAURRIETA',
            u'135 JAVIER',
            u'136 JUSLAPEÑA',
            u'138 LAKUNTZA',
            u'139 LANA',
            u'140 LANTZ',
            u'141 LAPOBLACIÓN',
            u'142 LARRAGA',
            u'143 LARRAONA',
            u'144 LARRAUN',
            u'145 LAZAGURRÍA',
            u'146 LEACHE/LEATXE',
            u'147 LEGARDA',
            u'148 LEGARIA',
            u'149 LEITZA',
            u'908 LEKUNBERRI',
            u'150 LEOZ/LEOTZ',
            u'151 LERGA',
            u'152 LERÍN',
            u'153 LESAKA',
            u'154 LEZAUN',
            u'155 LIÉDENA',
            u'156 LIZOÁIN-ARRIASGOITI/LIZOAIN-ARRIASGOITI',
            u'157 LODOSA',
            u'158 LÓNGUIDA/LONGIDA',
            u'029 LOS ARCOS',
            u'159 LUMBIER',
            u'160 LUQUIN',
            u'248 LUZAIDE/VALCARLOS',
            u'161 MAÑERU',
            u'162 MARAÑÓN',
            u'163 MARCILLA',
            u'164 MÉLIDA',
            u'165 MENDAVIA',
            u'166 MENDAZA',
            u'167 MENDIGORRIA',
            u'168 METAUTEN',
            u'169 MILAGRO',
            u'170 MIRAFUENTES',
            u'171 MIRANDA DE ARGA',
            u'172 MONREAL/ELO',
            u'173 MONTEAGUDO',
            u'174 MORENTIN',
            u'175 MUES',
            u'176 MURCHANTE',
            u'177 MURIETA',
            u'178 MURILLO EL CUENDE',
            u'179 MURILLO EL FRUTO',
            u'180 MURUZÁBAL',
            u'181 NAVASCUÉS/NABASKOZE',
            u'182 NAZAR',
            u'088 NOÁIN (VALLE DE ELORZ)/NOAIN (ELORTZIBAR)',
            u'183 OBANOS',
            u'185 OCHAGAVÍA/OTSAGABIA',
            u'184 OCO',
            u'186 ODIETA',
            u'187 OIZ',
            u'188 OLÁIBAR',
            u'189 OLAZTI/OLAZAGUTÍA',
            u'190 OLEJUA',
            u'191 OLITE/ERRIBERRI',
            u'192 OLÓRIZ/OLORITZ',
            u'195 ORBAIZETA',
            u'196 ORBARA',
            u'197 ORÍSOAIN',
            u'906 ORKOIEN',
            u'198 ORONZ/ORONTZE',
            u'199 OROZ-BETELU/OROTZ-BETELU',
            u'211 ORREAGA/RONCESVALLES',
            u'200 OTEIZA',
            u'201 PAMPLONA/IRUÑA',
            u'202 PERALTA/AZKOIEN',
            u'203 PETILLA DE ARAGÓN',
            u'204 PIEDRAMILLERA',
            u'205 PITILLAS',
            u'206 PUENTE LA REINA/GARES',
            u'207 PUEYO',
            u'208 RIBAFORADA',
            u'209 ROMANZADO',
            u'210 RONCAL/ERRONKARI',
            u'212 SADA',
            u'213 SALDIAS',
            u'214 SALINAS DE ORO/JAITZ',
            u'215 SAN ADRIÁN',
            u'217 SAN MARTÍN DE UNX',
            u'216 SANGÜESA/ZANGOZA',
            u'219 SANSOL',
            u'220 SANTACARA',
            u'222 SARRIÉS/SARTZE',
            u'223 SARTAGUDA',
            u'224 SESMA',
            u'225 SORLADA',
            u'226 SUNBILLA',
            u'227 TAFALLA',
            u'228 TIEBAS-MURUARTE DE RETA',
            u'229 TIRAPU',
            u'230 TORRALBA DEL RÍO',
            u'231 TORRES DEL RÍO',
            u'232 TUDELA',
            u'233 TULEBRAS',
            u'234 ÚCAR',
            u'123 UHARTE ARAKIL',
            u'235 UJUÉ/UXUE',
            u'236 ULTZAMA',
            u'237 UNCITI',
            u'238 UNZUÉ/UNTZUE',
            u'239 URDAZUBI/URDAX',
            u'240 URDIAIN',
            u'241 URRAÚL ALTO',
            u'242 URRAÚL BAJO',
            u'244 URROZ',
            u'243 URROZ-VILLA',
            u'245 URZAINQUI/URZAINKI',
            u'246 UTERGA',
            u'247 UZTÁRROZ/UZTARROZE',
            u'086 VALLE DE EGÜÉS/EGUESIBAR',
            u'194 VALLE DE OLLO/OLLARAN',
            u'260 VALLE DE YERRI/DEIERRI',
            u'249 VALTIERRA',
            u'251 VIANA',
            u'252 VIDÁNGOZ/BIDANKOZE',
            u'254 VILLAFRANCA',
            u'255 VILLAMAYOR DE MONJARDÍN',
            u'257 VILLATUERTA',
            u'258 VILLAVA/ATARRABIA',
            u'261 YESA',
            u'262 ZABALZA/ZABALTZA',
            u'073 ZIORDIA',
            u'907 ZIZUR MAYOR/ZIZUR NAGUSIA',
            u'263 ZUBIETA',
            u'264 ZUGARRAMURDI',
            u'265 ZÚÑIGA'
            ]
